"""
Green Test App - Environment Verification
Double-click to test if .exe can run on target PC without admin.
Tests: GUI, file read, file write, PDF detection, PDF autofill.
"""
import tkinter as tk
from tkinter import filedialog, messagebox
from pathlib import Path
import platform
import os
import sys

def get_app_dir():
    if getattr(sys, 'frozen', False):
        return Path(sys.executable).parent
    return Path(__file__).parent

def test_read_folder():
    folder = filedialog.askdirectory(title="Select a folder with PDF forms")
    if not folder:
        return

    folder_path = Path(folder)
    pdfs = list(folder_path.rglob("*.pdf"))
    subfolders = [f.name for f in folder_path.iterdir() if f.is_dir()]

    result = f"Folder: {folder}\n"
    result += f"Subfolders: {len(subfolders)}\n"
    for sf in subfolders[:10]:
        result += f"  - {sf}\n"
    result += f"\nPDFs found: {len(pdfs)}\n"
    for pdf in pdfs[:15]:
        size_kb = pdf.stat().st_size / 1024
        result += f"  - {pdf.relative_to(folder_path)} ({size_kb:.0f} KB)\n"
    if len(pdfs) > 15:
        result += f"  ... and {len(pdfs)-15} more\n"

    txt_result.delete("1.0", tk.END)
    txt_result.insert(tk.END, result)
    lbl_read_status.config(text="READ: OK", fg="green")

def test_write_file():
    app_dir = get_app_dir()
    test_file = app_dir / "zzz_write_test.txt"
    try:
        test_file.write_text("Write test OK\n")
        content = test_file.read_text()
        test_file.unlink()
        lbl_write_status.config(text=f"WRITE: OK ({app_dir})", fg="green")
    except PermissionError:
        lbl_write_status.config(text=f"WRITE: BLOCKED ({app_dir})", fg="red")
    except Exception as e:
        lbl_write_status.config(text=f"WRITE: ERROR - {e}", fg="red")

def test_pdf_write():
    folder = filedialog.askdirectory(title="Select output folder (e.g. pen drive)")
    if not folder:
        return
    out = Path(folder) / "zzz_pdf_test.txt"
    try:
        out.write_text("PDF output test OK\n")
        out.unlink()
        lbl_pdf_status.config(text=f"PDF OUTPUT: OK ({folder})", fg="green")
    except Exception as e:
        lbl_pdf_status.config(text=f"PDF OUTPUT: FAILED - {e}", fg="red")

def test_pdf_autofill():
    folder = filedialog.askdirectory(title="Select output folder for autofill test PDF")
    if not folder:
        return

    out_path = Path(folder) / "zzz_autofill_test.pdf"
    try:
        from reportlab.pdfgen import canvas
        from reportlab.lib.pagesizes import A4

        c = canvas.Canvas(str(out_path), pagesize=A4)
        width, height = A4

        c.setFont("Helvetica-Bold", 16)
        c.drawString(100, height - 100, "AUTOFILL TEST - Green Test App")

        c.setFont("Helvetica", 12)
        c.drawString(100, height - 140, "This PDF was generated by the form filler app.")
        c.drawString(100, height - 160, f"Platform: {platform.system()} {platform.release()}")
        c.drawString(100, height - 180, f"Python: {platform.python_version()}")
        c.drawString(100, height - 200, f"Output folder: {folder}")

        # Simulate form field writes at fixed coordinates
        fields = [
            ("Client Name:", "JOHN DOE", 100, height - 260),
            ("IC Number:", "880101-14-5678", 100, height - 285),
            ("Account No:", "2141-2900-000000", 100, height - 310),
            ("Date:", "2026-04-30", 100, height - 335),
            ("Amount:", "RM 10,000.00", 100, height - 360),
        ]
        c.setFont("Helvetica-Bold", 11)
        for label, value, x, y in fields:
            c.drawString(x, y, label)
            c.setFont("Helvetica", 11)
            c.drawString(x + 120, y, value)
            c.setFont("Helvetica-Bold", 11)

        c.setFont("Helvetica", 10)
        c.setFillColorRGB(0, 0.5, 0)
        c.drawString(100, height - 420, "All coordinate-based writes successful.")
        c.save()

        size_kb = out_path.stat().st_size / 1024
        lbl_autofill_status.config(
            text=f"AUTOFILL: OK - {out_path.name} ({size_kb:.0f} KB)",
            fg="green"
        )
        txt_result.delete("1.0", tk.END)
        txt_result.insert(tk.END, f"PDF autofill test PASSED\n\nSaved to: {out_path}\nSize: {size_kb:.0f} KB\n\nOpen the file to verify text positions are correct.")

    except ImportError:
        lbl_autofill_status.config(text="AUTOFILL: FAILED - reportlab not bundled", fg="red")
        txt_result.delete("1.0", tk.END)
        txt_result.insert(tk.END, "ERROR: reportlab library not found.\nThis .exe was not built with PDF support.")
    except Exception as e:
        lbl_autofill_status.config(text=f"AUTOFILL: ERROR - {e}", fg="red")
        txt_result.delete("1.0", tk.END)
        txt_result.insert(tk.END, f"Autofill error:\n{e}")

# --- GUI ---
root = tk.Tk()
root.title("Green Test - Form Filler Environment Check")
root.geometry("700x580")
root.resizable(True, True)

# System info
info = f"OS: {platform.system()} {platform.release()} | Python: {platform.python_version()} | Admin: {os.name}"
if platform.system() == "Windows":
    import ctypes
    is_admin = ctypes.windll.shell32.IsUserAnAdmin() != 0
    info += f" | Running as Admin: {is_admin}"
info += f"\nApp location: {get_app_dir()}"

lbl_info = tk.Label(root, text=info, justify=tk.LEFT, anchor="w", wraplength=680)
lbl_info.pack(fill=tk.X, padx=10, pady=(10,5))

# Test buttons frame
frm = tk.Frame(root)
frm.pack(fill=tk.X, padx=10, pady=5)

btn_read = tk.Button(frm, text="1. Test Read Folder", command=test_read_folder, width=22, height=2)
btn_read.grid(row=0, column=0, padx=5, pady=4)
lbl_read_status = tk.Label(frm, text="READ: not tested", fg="gray")
lbl_read_status.grid(row=0, column=1, sticky="w", padx=10)

btn_write = tk.Button(frm, text="2. Test Write (App Dir)", command=test_write_file, width=22, height=2)
btn_write.grid(row=1, column=0, padx=5, pady=4)
lbl_write_status = tk.Label(frm, text="WRITE: not tested", fg="gray")
lbl_write_status.grid(row=1, column=1, sticky="w", padx=10)

btn_pdf = tk.Button(frm, text="3. Test Output Folder", command=test_pdf_write, width=22, height=2)
btn_pdf.grid(row=2, column=0, padx=5, pady=4)
lbl_pdf_status = tk.Label(frm, text="PDF OUTPUT: not tested", fg="gray")
lbl_pdf_status.grid(row=2, column=1, sticky="w", padx=10)

btn_autofill = tk.Button(frm, text="4. Test PDF Autofill", command=test_pdf_autofill, width=22, height=2,
                          bg="#d4edda", activebackground="#a8d5b5")
btn_autofill.grid(row=3, column=0, padx=5, pady=4)
lbl_autofill_status = tk.Label(frm, text="AUTOFILL: not tested", fg="gray")
lbl_autofill_status.grid(row=3, column=1, sticky="w", padx=10)

# Results area
tk.Label(root, text="Results:", anchor="w").pack(fill=tk.X, padx=10, pady=(10,0))
txt_result = tk.Text(root, height=14, wrap=tk.WORD)
txt_result.pack(fill=tk.BOTH, expand=True, padx=10, pady=(0,10))

root.mainloop()
